#数据源连接信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/id4?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driverClassName: com.mysql.jdbc.Driver
migration:
